version: '3'
#https://www.digitalocean.com/community/tutorials/how-to-set-up-laravel-nginx-and-mysql-with-docker-compose-ru
services:
  app:
    build:
      context: dockerfile/app
      dockerfile: Dockerfile
#    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/project
    ports:
      - 25080:8080

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - ${WEBSERVICE_HTTP_PORT}:80
    volumes:
      - ./:/project
      - ./dockerfile/webserver/conf.d/:/etc/nginx/conf.d/
